name: Build MacOS and Windows image
on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [ main, master, dev ]

jobs:
    build-mac-package:
        runs-on: macos-latest  

        steps:
          - name: Check out repository code
            uses: actions/checkout@v3
            with:
              path: purple-hats

          - name: Grant execute permissions for user
            run: chmod ugo+rwx ./scripts/*.command ./scripts/*.sh
            working-directory: purple-hats

          - name: Copy scripts to parent directory
            run: |
              cp ./purple-hats/scripts/{*.command,*.sh}  ${{ github.workspace }}

          - name: Install Purple dependencies for MacOS
            run: |
              ./install_purple_dependencies.command

          - name: Zip entire Purple folder (Mac)
            run: |
              zip purple-hats-portable-mac.zip -y -r ./

          - name: Upload Mac artifact
            uses: actions/upload-artifact@v3
            with:
              name: purple-hats-portable-mac
              path: ./purple-hats-portable-mac.zip

          - name: Release Mac artifact
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
              files: |
                purple-hats-portable-mac.zip

    build-win-installer:
      runs-on: windows-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Download Purple HATS Backend
          shell : pwsh
          run: |
            $PHbackendUrl = "https://github.com/Georgetxm/purple-hats/releases/latest/download/purple-hats-portable-windows.zip"
            $BEdestinationPath = "$env:APPDATA\PHLatest.zip"
            $BEextractPath = "$env:APPDATA\Purple HATS Backend"
            Invoke-WebRequest -Uri $PHbackendUrl -OutFile $BEdestinationPath
            Expand-Archive -Path $BEdestinationPath -DestinationPath $BEextractPath -Force
            Remove-Item -Path $BEdestinationPath

        - name: Download Purple HATS Frontend
          shell : pwsh
          run: |
            $PHfrontendUrl = "https://github.com/Georgetxm/purple-hats-desktop/releases/latest/download/purple-hats-desktop-windows-prod.zip"
            $FEdestinationPath = "$env:APPDATA\Purple HATS-win32-x64.zip"
            $FEextractPath = "$env:APPDATA\Purple HATS-win32-x64"
            Invoke-WebRequest -Uri $PHfrontendUrl -OutFile $FEdestinationPath
            Expand-Archive -Path $FEdestinationPath -DestinationPath $FEextractPath -Force
            Remove-Item -Path $FEdestinationPath

        - name: Run Purple HATS Frontend
          run: |
            cd "$env:APPDATA\Purple HATS-win32-x64"
            ".\Purple HATS.exe"

        - name: Download Inno Setup 
          shell: pwsh
          run: |
            Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "$env:APPDATA\is.exe" 
            $env:path = "$env:path" + ";${env:programfiles(x86)}\Inno Setup 6"

        - name: Move Inno Setup script to APPDATA
          shell: pwsh
          run : Copy-Item -Path "./hats_for_windows.iss" -Destination "$env:APPDATA\hats_for_windows.iss" -Force

        - name: Execute Inno Setup script to run installer
          shell: pwsh
          run: ISCC /O"${env:APPDATA}" "$env:APPDATA\hats_for_windows.iss"

        - name: Create folder
          run: |
            cd $env:APPDATA
            mkdir setup
            move mysetup.exe setup/Purple-Hats-Setup.exe

        - name: Get AppData Directory
          run: echo ("APPDATA_DIR=" + $env:APPDATA) >> $env:GITHUB_ENV

        - name: Upload Purple HATS setup artifact
          uses: actions/upload-artifact@v3
          with:
            name: purpleHATSSetup
            path: ${{ env.APPDATA_DIR }}/setup




