name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest  

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        path: purple-hats-desktop
    
    - name: Install NPM packages 
      run:
        npm ci  

    - name: Install Playwright browsers and dependencies
      run: 
        npx playwright install --with-deps

    - name: Build Application 
      run: npm run build
    
    - name: Run Playwright tests
      run: npx playwright test --workers 1
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
