name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest  

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        path: purple-hats-desktop
    
    - name: Update NPM to the latest version
      run: 
        npm install -g npm@latest 
    
    - name: Clean NPM cache 
      run: 
        npm cache clean --force 
    
    - name: Delete node modules and package-lock.json 
      run: 
        npm rm -rf node_modules && rm package-lock.json

    - name: Install NPM packages 
      run:
        npm install  

    - name: Install Playwright browsers and dependencies
      run: 
        npx playwright install --with-deps

    - name: Build Application 
      run: npm run build
    
    - name: Run Playwright tests
      run: npx playwright test --workers 1 --trace on
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
